name: Publish to GH Pages

   on:
     push:
       branches: [main]
     pull_request:

   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout source
           uses: actions/checkout@v3
           with:
             submodules: true

         - name: Checkout destination
           if: github.ref == 'refs/heads/main'
           uses: actions/checkout@v3
           with:
             ref: gh-pages
             path: built-site

         - name: Setup Hugo
           env:
             HUGO_VERSION: 0.133.1
           run: |
             wget -O ${{ runner.temp }}/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz
             tar -xf ${{ runner.temp }}/hugo.tar.gz -C ${{ runner.temp }}
             sudo mv ${{ runner.temp }}/hugo /usr/local/bin/hugo
             rm ${{ runner.temp }}/hugo.tar.gz

         - name: Build
           run: hugo

         - name: Deploy
           if: github.ref == 'refs/heads/main'
           run: |
             cp -R public/* built-site/
             cd built-site
             git config user.name 'incendies'
             git config user.email 'yunusemreozdiyar@gmail.com'
             git add .
             git commit -m 'Updated site' || echo "No changes to commit"
             git push